### PR TITLE
Add action to copy email addresses to kill ring.

### PR DESCRIPTION
**Pull request by slackorama**
Admittedly, this scratches my own itch but I _think_ it's handy.

Also fixes an issue I had with the formatting of contacts with commas in their names.

### CODE REVIEW

**Comment by tmalsburg** [comment]
Contributions that scratch someone's own itch are usually the best.

One question about terminology: You use "clipboard" in the name of the action but "kill ring" in the comments. My understanding is that "clipboard" is typically used to refer to the system-wide copy-and-paste facility but "kill ring" for Emacs-internal facilities.  Is that correct?

Your code does not affect the system-wide clipboard AFAICT.  Wouldn't it be more useful if the email address was also available for pasting in apps other than Emacs?

**Comment by slackorama** [comment]
You are correct. I swap kill-ring and clipboard too much.

Using emacs 24 so it should go to the clipboard on a kill:  https://www.gnu.org/software/emacs/manual/html_node/emacs/Clipboard.html Unless I'm misunderstanding something.

I think it can be done with `gui-set-selection` in older versions. I'll try and get it rigged up and submit a new PR with changes for both.

**Comment by tmalsburg** [comment]
Just checked: With a recent development Emacs and `emacs -Q`, `(kill-new "XYZ")` does give me "XYZ" when I paste in another application.  My non-Q Emacs was configured to leave the system-wide clipboard untouched.

**Comment by Ambrevar** [comment]
Isn't this PR obsolete? I have a `Copy to clipboard` action in `helm-mu-contacts`.

**Comment by tmalsburg** [comment]
Yes, seems outdated.

**Pull request closed without merging**
