### PR TITLE
Add option to skip duplicates while searching mail

### PR DESCRIPTION
**Pull request by xuchunyang**

### CODE REVIEW

**Comment by tmalsburg** [comment]
This doesn't work because `--skip-dups` doesn't take true or false.  Your code always skips duplicates no matter what the value of the configuration variable is.  See the man page of mu-find.

**Comment by xuchunyang** [comment]
You are right, I'm fixing it now.

**Comment by xuchunyang** [comment]
It should works now.

**Comment by tmalsburg** [comment]
Great, thanks.

**Pull request merged**
